rapsodo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: rapsodo
      password: rapsodo_password
      port: 5432
      dbname: rapsodo_db
      schema: public